### PR TITLE
Added fermionic creation-/annihilation operators (and more!)

### PR DESCRIPTION
**Pull request by JonasRigo**
In this update fermionic creation-/annihilation operators and number operators are natively added to jVMC.
For usage examples refer to `ex8_fermions.py`.

### CODE REVIEW

**Comment by markusschmitt** [comment]
There are actually a few more new features:
- A transformer architecture (`GPT`)
- An `Infidelity` operator to compute (in-)fidelities between states; also a `Target` NQS architecture that corresponds to a full state vector
- New utilities to automatically save parameter dictionaries to HDF5 (`Parameters2HDF5.py`)

Before merging, we need some tests, at least for the Fermionic operators, ideally also for the infidelity and a check whether the transformer is normalized.

Also, some MacOS system files made their way into the repo. They should be removed.

**Comment by JonasRigo** [comment]
The `Infidelity.py`, `gpt.py`, `Parameters2HDF5.py` and `Target.py` files were removed form the pull request and reserved for a later pull request.
As requested tests were added for the fermionic operators in `operator_test.py` and the floating point arithmetic operation to compute the the Jordan-Wigner phase was replaced with pure integer arithmetic operations.
Finally all `.DS_Store` files were deleted.

**Comment by JonasRigo** [comment]
The `Infidelity.py`, `gpt.py`, `Parameters2HDF5.py` and `Target.py` files were removed form the pull request and reserved for a later pull request.
Tests were added for the fermionic operators in `operator_test.py` and the floating point arithmetic operation to compute the Jordan-Wigner phase was replaced with pure integer arithmetic operations.
Finally all `.DS_Store` files were deleted.

**Comment by JonasRigo** [comment]
Adding fermionic operators to jVMC, corresponding example and tests. All tests ran successfully and the example is streamlined.

**Pull request merged**
